language: c
compiler:
  - gcc
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install autoconf
  - sudo apt-get install build-essential
  - sudo apt-get install gperf
  - sudo apt-get install libgd2-xpm-dev
  - sudo apt-get install devscripts
  - sudo apt-get install dh-make
script:
  - ./configure    || exit 1
  - make           || exit 1
  - mkdir _install || exit 1
  - make install DESTDIR=$(pwd)/_install || exit 1
  - make deb
notification:
  irc:
    channels:
      - "chat.freenode.net#naemon-devel"
    on_success: change
    on_failure: always
  email:
    - ozamosi@flukkost.nu
